version: 2

updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
