[package]
name = "interrupts"
version = "0.2.0"
edition = "2024"
description = "Cross-architecture utilities for temporarily disabling interrupts."
repository = "https://github.com/mkroening/interrupts"
license = "MIT OR Apache-2.0"
keywords = ["interrupts", "disable", "without"]
categories = ["no-std::no-alloc"]
